# Generated by Django 5.2.4 on 2025-07-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inicio", "0002_etiqueta"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacion",
            name="etiquetas_favoritas",
            field=models.ManyToManyField(blank=True, to="inicio.etiqueta"),
        ),
        migrations.AddField(
            model_name="voluntario",
            name="etiquetas_favoritas",
            field=models.ManyToManyField(blank=True, to="inicio.etiqueta"),
        ),
    ]
