# Generated by Django 5.2.4 on 2025-07-16 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inicio", "0004_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organizacion",
            options={"verbose_name_plural": "Organizaciones"},
        ),
    ]
