# Generated by Django 5.2.4 on 2025-07-16 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inicio", "0005_alter_organizacion_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacion",
            name="descripcion",
            field=models.TextField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Seguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_seguimiento", models.DateTimeField(auto_now_add=True)),
                (
                    "seguido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguidores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seguidor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Seguimientos",
                "unique_together": {("seguidor", "seguido")},
            },
        ),
    ]
