# Generated by Django 5.2.4 on 2025-07-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inicio", "0006_organizacion_descripcion_seguimiento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizacion",
            name="descripcion",
            field=models.TextField(default="", max_length=500),
        ),
    ]
