# Generated by Django 5.2.4 on 2025-07-16 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inicio", "0007_alter_organizacion_descripcion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-fecha_creacion"]},
        ),
        migrations.AlterModelOptions(
            name="seguimiento",
            options={},
        ),
        migrations.RenameField(
            model_name="organizacion",
            old_name="user",
            new_name="usuario",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="content",
            new_name="contenido",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="comments_count",
            new_name="conteo_comentarios",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="likes_count",
            new_name="conteo_likes",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="is_deleted",
            new_name="esta_eliminado",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="etiqueta",
            new_name="etiquetas",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="created_at",
            new_name="fecha_creacion",
        ),
        migrations.RenameField(
            model_name="voluntario",
            old_name="user",
            new_name="usuario",
        ),
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.AddField(
            model_name="post",
            name="autor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts_creados",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenido", models.TextField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comentarios",
                        to="inicio.post",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Comentarios",
                "ordering": ["fecha_creacion"],
            },
        ),
    ]
