# Generated by Django 5.2.4 on 2025-07-16 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inicio", "0008_alter_post_options_alter_seguimiento_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="voluntario",
            old_name="usuario",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="organizacion",
            name="usuario",
        ),
        migrations.AddField(
            model_name="organizacion",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="etiquetas",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="inicio.etiqueta"
            ),
        ),
    ]
