# Generated by Django 5.2.4 on 2025-07-17 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inicio", "0011_notificacion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notificacion",
            old_name="is_read",
            new_name="leido",
        ),
    ]
